apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: memos
  name: memos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: memos
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/wave-net: "true"
        io.kompose.service: memos
    spec:
      containers:
        - image: neosmemo/memos:stable
          name: memos
          ports:
            - containerPort: 5230
              hostPort: 5230
              protocol: TCP
          volumeMounts:
            - mountPath: /var/opt/memos
              name: efs-claim
      restartPolicy: Always
      volumes:
        - name: efs-claim
          persistentVolumeClaim:
            claimName: efs-claim
