services:
  test-rabbit:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 200M
    image: "rabbitmq:3-management"
    container_name: test-rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 3
    # restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      wave-net:
        aliases:
          - test-rabbit

  test-redis:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 500M
    image: redis:6.0.9-alpine
    command: redis-server --requirepass rIGFUsDCrhzijfTR
    container_name: test-redis
    hostname: test-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "rIGFUsDCrhzijfTR", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    # restart: always
    ports:
      - "6379:6379"
    volumes:
      - /home/going/work/docker-env/data/redis:/data
    networks:
      wave-net:
        aliases:
          - test-redis

  test-mysql:
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 200M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 200M
    # image: mysql:5.7
    image: mysql:8
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # MYSQL_USER: root
      MYSQL_PASSWORD: stadmin
      MYSQL_ROOT_PASSWORD: stadmin
    container_name: test-mysql
    hostname: test-mysql
    ports:
      - 3306:3306
    volumes:
      # - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - /home/going/work/docker-env/data/mysql:/var/lib/mysql
    networks:
      wave-net:
        aliases:
          - test-mysql

networks:
  wave-net:
    external: true
